{% set name = "hepstats" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hepstats-{{ version }}.tar.gz
  sha256: 5c5af54a845332e9e2f27d5899c680f9f425f16ab9e16683d1bf80dd9ca8ec14

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch.vcs
  run:
    - asdf
    - numpy
    - pandas
    - python >={{ python_min }}
    - scipy
    - tqdm
    - uhi
  run_constraint:
    - zfit >= 0.20.0

test:
  imports:
    - hepstats
    - hepstats.hypotests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://scikit-hep.org/hepstats/
  summary: statistics tools and utilities
  license: BSD-3-Clause
  license_file:
    - LICENSES/LICENSE
    - LICENSES/LICENSE_ASTROML.rst
  dev_url: https://github.com/scikit-hep/hepstats
  doc_url: https://scikit-hep.org/hepstats/

extra:
  recipe-maintainers:
    - jonas-eschle
    - chrisburr
