{% set name = "hepstats" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hepstats-{{ version }}.tar.gz
  sha256: dae50a739afb4e80c4118bbd13ff1c959d9de96b45fd9cab31a75f4b96b66288

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    - asdf
    - numpy
    - pandas
    - python >=3.7
    - scipy
    - tqdm
    - uhi

test:
  imports:
    - hepstats
    - hepstats.hypotests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://scikit-hep.org/hepstats/
  summary: statistics tools and utilities
  license: BSD-3-Clause
  license_file:
    - LICENSES/LICENSE
    - LICENSES/LICENSE_ASTROML.rst
  dev_url: https://github.com/scikit-hep/hepstats
  doc_url: https://scikit-hep.org/hepstats/

extra:
  recipe-maintainers:
    - jonas-eschle
    - chrisburr
